CREATE TABLE IF NOT EXISTS voyage (
    voyage_number   VARCHAR(20)  NOT NULL PRIMARY KEY,
    carrier_code    VARCHAR(10)  NOT NULL,
    carrier_name    VARCHAR(200) NOT NULL,
    ship_name       VARCHAR(200) NOT NULL,
    departure_date  TIMESTAMP    NOT NULL,
    arrival_date    TIMESTAMP    NOT NULL,
    origin_unlocode VARCHAR(5)   NOT NULL,
    dest_unlocode   VARCHAR(5)   NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'SCHEDULED',
    registered_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version         BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS carrier_movement (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_number      VARCHAR(20) NOT NULL REFERENCES voyage(voyage_number),
    movement_seq       INTEGER     NOT NULL,
    departure_unlocode VARCHAR(5)  NOT NULL,
    arrival_unlocode   VARCHAR(5)  NOT NULL,
    departure_time     TIMESTAMP   NOT NULL,
    arrival_time       TIMESTAMP   NOT NULL,
    UNIQUE (voyage_number, movement_seq)
);

CREATE TABLE IF NOT EXISTS voyage_accepted_cargo_type (
    voyage_number VARCHAR(20) NOT NULL REFERENCES voyage(voyage_number),
    cargo_type    VARCHAR(16) NOT NULL,
    PRIMARY KEY (voyage_number, cargo_type)
);
