apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cargo-tracker
spec:
  ingressClassName: nginx
  rules:
    - host: cargo-monolith.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: cargo-tracker
                port:
                  number: 80
