apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cargo-axon
spec:
  ingressClassName: nginx
  rules:
    - host: cargo-axon.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: frontend
                port:
                  number: 80
