-- Axon Framework が必要とするテーブル（PostgreSQL 用）
CREATE TABLE IF NOT EXISTS tokenentry (
    processorname VARCHAR(255) NOT NULL,
    segment       INTEGER      NOT NULL,
    token         BYTEA,
    tokentype     VARCHAR(255),
    timestamp     VARCHAR(255),
    owner         VARCHAR(255),
    PRIMARY KEY (processorname, segment)
);

CREATE TABLE IF NOT EXISTS domainevententry (
    globalindex         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aggregateidentifier VARCHAR(255) NOT NULL,
    sequencenumber      BIGINT       NOT NULL,
    type                VARCHAR(255),
    eventidentifier     VARCHAR(255) NOT NULL UNIQUE,
    metadata            BYTEA,
    payload             BYTEA        NOT NULL,
    payloadrevision     VARCHAR(255),
    payloadtype         VARCHAR(255) NOT NULL,
    timestamp           VARCHAR(255) NOT NULL,
    PRIMARY KEY (globalindex)
);

CREATE TABLE IF NOT EXISTS snapshotevententry (
    aggregateidentifier VARCHAR(255) NOT NULL,
    sequencenumber      BIGINT       NOT NULL,
    type                VARCHAR(255) NOT NULL,
    eventidentifier     VARCHAR(255) NOT NULL UNIQUE,
    metadata            BYTEA,
    payload             BYTEA        NOT NULL,
    payloadrevision     VARCHAR(255),
    payloadtype         VARCHAR(255) NOT NULL,
    timestamp           VARCHAR(255) NOT NULL,
    PRIMARY KEY (aggregateidentifier, sequencenumber, type)
);

CREATE TABLE IF NOT EXISTS sagaentry (
    sagaid        VARCHAR(255) NOT NULL,
    revision      VARCHAR(255),
    sagatype      VARCHAR(255),
    serializedsaga BYTEA,
    PRIMARY KEY (sagaid)
);

CREATE TABLE IF NOT EXISTS associationvalueentry (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    associationkey    VARCHAR(255) NOT NULL,
    associationvalue  VARCHAR(255),
    sagaid            VARCHAR(255) NOT NULL,
    sagatype          VARCHAR(255),
    PRIMARY KEY (id)
);
