-- location テーブル（UN/LOCODE による港湾・空港の共有カーネル）
CREATE TABLE IF NOT EXISTS location (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unlocode     VARCHAR(5)   NOT NULL,
    name         VARCHAR(100) NOT NULL,
    country_code VARCHAR(2),
    time_zone    VARCHAR(50),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_location_unlocode UNIQUE (unlocode)
);

-- 初期データ（主要港湾）
INSERT INTO location (unlocode, name, country_code, time_zone) VALUES
    ('JPTYO', '東京港', 'JP', 'Asia/Tokyo'),
    ('JPOSE', '大阪港', 'JP', 'Asia/Tokyo'),
    ('JPNGO', '名古屋港', 'JP', 'Asia/Tokyo'),
    ('JPYOK', '横浜港', 'JP', 'Asia/Tokyo'),
    ('CNSHA', '上海港', 'CN', 'Asia/Shanghai'),
    ('CNSHK', '深圳（蛇口）港', 'CN', 'Asia/Shanghai'),
    ('SGSIN', 'シンガポール港', 'SG', 'Asia/Singapore'),
    ('HKHKG', '香港港', 'HK', 'Asia/Hong_Kong'),
    ('USLAX', 'ロサンゼルス港', 'US', 'America/Los_Angeles'),
    ('USNYC', 'ニューヨーク港', 'US', 'America/New_York'),
    ('DEHAM', 'ハンブルク港', 'DE', 'Europe/Berlin'),
    ('NLRTM', 'ロッテルダム港', 'NL', 'Europe/Amsterdam');
