-- cargo テーブル（貨物予約）
CREATE TABLE IF NOT EXISTS cargo (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id              UUID          NOT NULL,
    shipper_id              UUID          NOT NULL,
    cargo_type              VARCHAR(30)   NOT NULL,
    weight                  NUMERIC(10,3) NOT NULL,
    origin_unlocode         VARCHAR(5)    NOT NULL,
    destination_unlocode    VARCHAR(5)    NOT NULL,
    arrival_deadline        DATE          NOT NULL,
    booking_status          VARCHAR(30)   NOT NULL DEFAULT 'PRELIMINARY',
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_cargo_booking_id UNIQUE (booking_id),
    CONSTRAINT chk_cargo_type CHECK (cargo_type IN ('GENERAL', 'HAZARDOUS', 'REFRIGERATED')),
    CONSTRAINT chk_booking_status CHECK (booking_status IN (
        'PRELIMINARY', 'ROUTE_PROPOSED', 'CONFIRMED', 'TRACKING_ISSUED',
        'IN_TRANSIT', 'DELIVERED', 'SETTLED', 'CANCELLED'
    )),
    CONSTRAINT chk_weight_positive CHECK (weight > 0),
    CONSTRAINT fk_cargo_shipper FOREIGN KEY (shipper_id)
        REFERENCES shipper (id)
);
