-- Routing Context: voyage テーブル（航海集約ルート）
CREATE TABLE voyage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_number VARCHAR(20) NOT NULL UNIQUE
);

-- Routing Context: carrier_movement テーブル（運送区間）
CREATE TABLE carrier_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_id BIGINT NOT NULL REFERENCES voyage(id) ON DELETE CASCADE,
    departure_location_unlocode VARCHAR(5) NOT NULL,
    arrival_location_unlocode VARCHAR(5) NOT NULL,
    departure_date TIMESTAMP NOT NULL,
    arrival_date TIMESTAMP NOT NULL
);

-- テストデータ: 東京 → ニューヨーク直行便
INSERT INTO voyage (voyage_number) VALUES ('V001');
INSERT INTO carrier_movement (voyage_id, departure_location_unlocode, arrival_location_unlocode, departure_date, arrival_date)
VALUES (
    (SELECT id FROM voyage WHERE voyage_number = 'V001'),
    'JPTYO', 'USNYC',
    '2026-05-10 09:00:00',
    '2026-06-10 14:00:00'
);

-- テストデータ: 東京 → 上海 → ニューヨーク
INSERT INTO voyage (voyage_number) VALUES ('V002');
INSERT INTO carrier_movement (voyage_id, departure_location_unlocode, arrival_location_unlocode, departure_date, arrival_date)
VALUES (
    (SELECT id FROM voyage WHERE voyage_number = 'V002'),
    'JPTYO', 'CNSHA',
    '2026-05-15 10:00:00',
    '2026-05-22 08:00:00'
);
INSERT INTO carrier_movement (voyage_id, departure_location_unlocode, arrival_location_unlocode, departure_date, arrival_date)
VALUES (
    (SELECT id FROM voyage WHERE voyage_number = 'V002'),
    'CNSHA', 'USNYC',
    '2026-05-24 12:00:00',
    '2026-06-20 16:00:00'
);

-- テストデータ: 東京 → ロサンゼルス直行便
INSERT INTO voyage (voyage_number) VALUES ('V003');
INSERT INTO carrier_movement (voyage_id, departure_location_unlocode, arrival_location_unlocode, departure_date, arrival_date)
VALUES (
    (SELECT id FROM voyage WHERE voyage_number = 'V003'),
    'JPTYO', 'USLAX',
    '2026-05-20 08:00:00',
    '2026-06-05 18:00:00'
);
