# routingms 共通設定
spring:
  application:
    name: routingms
  profiles:
    active: local-h2
  mvc:
    problemdetails:
      enabled: true

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when_authorized

# Axon 共通設定（プロファイル別に上書き）
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
