-- V002: tracking_summary / tracking_event / tracking_exception / cargo_snapshot 作成
--
-- TrackingActivity Aggregate（Axon Event Sourcing）の Read Model。
-- TrackingProjectionsEventHandler が以下のイベントを購読して INSERT/UPDATE する:
--   - bookingms.CargoTrackedEvent  → tracking_summary 初期化
--   - trackingms.TrackingInitializedEvent → 同上
--   - handlingms.HandlingActivityRegisteredEvent → tracking_event INSERT + 状態反映
--   - trackingms.TransportStatusUpdatedEvent → tracking_event INSERT + 状態反映
--
-- 設計準拠: docs/development/iteration_plan-6.md L460-528（データモデル）
--          docs/design/data-model.md L513-556（tracking_*）
-- 関連 ADR: ADR-0012 / ADR-0013

CREATE TABLE IF NOT EXISTS tracking_summary (
    tracking_number       VARCHAR(25)   NOT NULL PRIMARY KEY,
    booking_id            VARCHAR(36)   NOT NULL,
    current_status        VARCHAR(20)   NOT NULL,
    current_unlocode      VARCHAR(5),
    current_voyage_number VARCHAR(20),
    origin_unlocode       VARCHAR(5)    NOT NULL,
    destination_unlocode  VARCHAR(5)    NOT NULL,
    estimated_arrival     TIMESTAMP,
    delivered_at          TIMESTAMP,
    misrouted             BOOLEAN       NOT NULL DEFAULT FALSE,
    last_event_at         TIMESTAMP,
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version               BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uk_tracking_summary_booking_id UNIQUE (booking_id),
    CONSTRAINT chk_tracking_summary_status
        CHECK (current_status IN ('NOT_RECEIVED', 'RECEIVED', 'LOADED', 'IN_TRANSIT',
                                  'UNLOADED', 'AWAITING_CLAIM', 'DELIVERED',
                                  'MISROUTED', 'EXCEPTION'))
);

CREATE INDEX IF NOT EXISTS idx_tracking_summary_booking_id
    ON tracking_summary (booking_id);
CREATE INDEX IF NOT EXISTS idx_tracking_summary_current_status
    ON tracking_summary (current_status);

CREATE TABLE IF NOT EXISTS tracking_event (
    event_id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_number   VARCHAR(25)   NOT NULL,
    occurred_at       TIMESTAMP     NOT NULL,
    recorded_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_type        VARCHAR(40)   NOT NULL,
    transport_status  VARCHAR(20),
    unlocode          VARCHAR(5),
    voyage_number     VARCHAR(20),
    handling_type     VARCHAR(16),
    description       TEXT,
    source            VARCHAR(20)   NOT NULL,
    CONSTRAINT fk_tracking_event_summary
        FOREIGN KEY (tracking_number) REFERENCES tracking_summary(tracking_number)
        ON DELETE CASCADE,
    CONSTRAINT chk_tracking_event_source
        CHECK (source IN ('HANDLING', 'MANUAL', 'SYSTEM'))
);

CREATE INDEX IF NOT EXISTS idx_tracking_event_tracking_number_occurred_at
    ON tracking_event (tracking_number, occurred_at);
CREATE INDEX IF NOT EXISTS idx_tracking_event_source
    ON tracking_event (source);

CREATE TABLE IF NOT EXISTS tracking_exception (
    exception_id      VARCHAR(36)   NOT NULL PRIMARY KEY,
    tracking_number   VARCHAR(25)   NOT NULL,
    exception_type    VARCHAR(16)   NOT NULL,
    occurred_at       TIMESTAMP     NOT NULL,
    occurred_unlocode VARCHAR(5),
    description       TEXT          NOT NULL,
    response_status   VARCHAR(16)   NOT NULL,
    resolution        TEXT,
    resolved_at       TIMESTAMP,
    escalated         BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tracking_exception_summary
        FOREIGN KEY (tracking_number) REFERENCES tracking_summary(tracking_number)
        ON DELETE CASCADE,
    CONSTRAINT chk_tracking_exception_response_status
        CHECK (response_status IN ('PENDING', 'INVESTIGATING', 'RESOLVED', 'ESCALATED'))
);

CREATE INDEX IF NOT EXISTS idx_tracking_exception_tracking_number
    ON tracking_exception (tracking_number);

-- CargoSnapshot ACL（trackingms 側）: Booking Context の CargoBookedEvent / CargoRoutedEvent
-- / CargoTrackedEvent を購読して維持する（ADR-0012 / TI06 で Event 駆動 ACL を本実装）
CREATE TABLE IF NOT EXISTS cargo_snapshot (
    booking_id            VARCHAR(36)   NOT NULL PRIMARY KEY,
    tracking_number       VARCHAR(25),
    origin_unlocode       VARCHAR(5)    NOT NULL,
    destination_unlocode  VARCHAR(5)    NOT NULL,
    cargo_type            VARCHAR(16)   NOT NULL,
    arrival_deadline      DATE,
    booking_status        VARCHAR(20)   NOT NULL,
    updated_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_cargo_snapshot_cargo_type_trk
        CHECK (cargo_type IN ('GENERAL', 'HAZARDOUS', 'REFRIGERATED'))
);

CREATE INDEX IF NOT EXISTS idx_cargo_snapshot_trk_tracking_number
    ON cargo_snapshot (tracking_number);
