export const APP_NAME = 'Cargo Tracker'

export const BOOKING_STATUS = {
  PRELIMINARY: 'PRELIMINARY',
  ROUTE_PROPOSED: 'ROUTE_PROPOSED',
  CONFIRMED: 'CONFIRMED',
  TRACKING_ISSUED: 'TRACKING_ISSUED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  SETTLED: 'SETTLED',
  CANCELLED: 'CANCELLED',
} as const

export const TRANSPORT_STATUS = {
  NOT_RECEIVED: 'NOT_RECEIVED',
  RECEIVED: 'RECEIVED',
  LOADED: 'LOADED',
  IN_TRANSIT: 'IN_TRANSIT',
  UNLOADED: 'UNLOADED',
  AWAITING_CLAIM: 'AWAITING_CLAIM',
  DELIVERED: 'DELIVERED',
  MISROUTED: 'MISROUTED',
} as const
