-- trackingms Read Model（IT5 US14・US17・US18 / US19・US20）
-- data-model.md tracking_read_db の ER 図と整合。
-- 監査カラム（created_at / updated_at / version）は他サービスと同様に明示する。

-- tracking_summary: TrackingActivity 集約の Read Model（最新状態のみ保持）
CREATE TABLE IF NOT EXISTS tracking_summary (
    tracking_number       VARCHAR(25)  NOT NULL,
    booking_id            VARCHAR(36)  NOT NULL,
    current_status        VARCHAR(20)  NOT NULL,  -- 9 値: NOT_RECEIVED ... DELIVERED / MISROUTED / EXCEPTION
    current_unlocode      VARCHAR(5),
    current_voyage_number VARCHAR(20),
    estimated_arrival     TIMESTAMP,
    misrouted             BOOLEAN      NOT NULL DEFAULT FALSE,
    last_event_at         TIMESTAMP,
    delivered_at          TIMESTAMP,                          -- JWT 有効期限計算用（ADR-0013 想定）
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version               BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (tracking_number),
    CONSTRAINT uk_tracking_summary_booking_id UNIQUE (booking_id)
);

CREATE INDEX IF NOT EXISTS idx_tracking_summary_status ON tracking_summary (current_status);
CREATE INDEX IF NOT EXISTS idx_tracking_summary_misrouted ON tracking_summary (misrouted);

-- tracking_event: 追跡イベント履歴（時系列・挿入のみ更新なし）
CREATE TABLE IF NOT EXISTS tracking_event (
    event_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tracking_number  VARCHAR(25)  NOT NULL,
    occurred_at      TIMESTAMP    NOT NULL,
    recorded_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_type       VARCHAR(40)  NOT NULL,  -- TRACKING_INITIALIZED / STATUS_UPDATED / EXCEPTION_REGISTERED ...
    transport_status VARCHAR(20),
    unlocode         VARCHAR(5),
    voyage_number    VARCHAR(20),
    handling_type    VARCHAR(16),
    source           VARCHAR(16),            -- HANDLING / MANUAL / SYSTEM（IT6 拡張）
    description      VARCHAR(1000),
    PRIMARY KEY (event_id)
);

CREATE INDEX IF NOT EXISTS idx_tracking_event_number_occurred ON tracking_event (tracking_number, occurred_at);
CREATE INDEX IF NOT EXISTS idx_tracking_event_type_recorded ON tracking_event (event_type, recorded_at);

-- tracking_exception: 追跡例外（IT6 US19・US20 / 遅延・破損・紛失）
-- IT5 では未使用だが、スキーマだけ先行作成してフォローアップマイグレーションを不要にする
CREATE TABLE IF NOT EXISTS tracking_exception (
    exception_id        VARCHAR(36)  NOT NULL,
    tracking_number     VARCHAR(25)  NOT NULL,
    exception_type      VARCHAR(16)  NOT NULL,  -- DELAY / DAMAGE / LOSS
    occurred_at         TIMESTAMP    NOT NULL,
    occurred_unlocode   VARCHAR(5),
    description         VARCHAR(1000) NOT NULL,
    response_status     VARCHAR(16)  NOT NULL,  -- REPORTED / RESPONDING / RESOLVED
    resolution          VARCHAR(1000),
    resolved_at         TIMESTAMP,
    escalated           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (exception_id)
);

CREATE INDEX IF NOT EXISTS idx_tracking_exception_number_status ON tracking_exception (tracking_number, response_status);
