CREATE TABLE IF NOT EXISTS shipper (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipper_code    VARCHAR(20)    NOT NULL UNIQUE,
    shipper_type    VARCHAR(20)    NOT NULL,
    name            VARCHAR(200)   NOT NULL,
    email           VARCHAR(200)   NOT NULL UNIQUE,
    phone           VARCHAR(50),
    contract_number VARCHAR(50),
    discount_rate   DECIMAL(5,4),
    created_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);
