-- Axon Framework が必要とするテーブル（PostgreSQL 用、H2 互換）
-- handlingms / trackingms と同等パターン（IT5 で確立、新サービス追加チェックリスト IT7 改訂版 §6 準拠）
-- Saga は使わず Invoice 単一集約で集約発火型のため sagaentry / associationvalueentry は作らない（ADR-0012/0015）。

CREATE TABLE IF NOT EXISTS tokenentry (
    processorname VARCHAR(255) NOT NULL,
    segment       INTEGER      NOT NULL,
    token         BYTEA,
    tokentype     VARCHAR(255),
    timestamp     VARCHAR(255),
    owner         VARCHAR(255),
    PRIMARY KEY (processorname, segment)
);

CREATE TABLE IF NOT EXISTS domainevententry (
    globalindex         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aggregateidentifier VARCHAR(255) NOT NULL,
    sequencenumber      BIGINT       NOT NULL,
    type                VARCHAR(255),
    eventidentifier     VARCHAR(255) NOT NULL UNIQUE,
    metadata            BYTEA,
    payload             BYTEA        NOT NULL,
    payloadrevision     VARCHAR(255),
    payloadtype         VARCHAR(255) NOT NULL,
    timestamp           VARCHAR(255) NOT NULL,
    PRIMARY KEY (globalindex)
);

CREATE TABLE IF NOT EXISTS snapshotevententry (
    aggregateidentifier VARCHAR(255) NOT NULL,
    sequencenumber      BIGINT       NOT NULL,
    type                VARCHAR(255) NOT NULL,
    eventidentifier     VARCHAR(255) NOT NULL UNIQUE,
    metadata            BYTEA,
    payload             BYTEA        NOT NULL,
    payloadrevision     VARCHAR(255),
    payloadtype         VARCHAR(255) NOT NULL,
    timestamp           VARCHAR(255) NOT NULL,
    PRIMARY KEY (aggregateidentifier, sequencenumber, type)
);
