apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_USERNAME: cargo_tracker
  DB_PASSWORD: cargo_tracker
  POSTGRES_USER: cargo_tracker
  POSTGRES_PASSWORD: cargo_tracker
